# Дескриптивна статистика

##                 Варіант 10


### Завдання виконала 
### студентка 3 курсу статистики 
### (група комп'ютерна статистика)
### механіко-математичного факультету
### КНУ ім. Т.Г. Шевченка

##           Москанова Ольга

# Завдання 1

### Дані:

Місто | Ахмедабад | Делі | Ченнаї | Колката | Мумбаї | Хайдарабад | Каннур
----- | --------- | ---- | ------ | ------- | ------ | ---------- | -----
McDonalds | 200.00 | 250.00 | 250.00 | 300.00 | 289.50 | 300.00 | 250.00
Молоко 1gln | 195.53 | 187.99 | 178.47 | 151.13 | 205.85 | 185.31 | 151.42



In [1]:
# initialize data
mac_prices  = c(200.,    250.,   250.,   300.,   289.5, 300.,   250)
milk_prices = c(195.53, 187.99, 178.47, 151.13, 205.85, 185.31, 151.42)

### Обчислити:
* вибіркове середнє
* середнє геометричне
* середнє гармонійне
* медіану
* середину діапазону
* дисперсію
* середньоквадратичне відхилення
* інтерквартильний розмах
* ширину діапазону
* коефіцієнт варіації

#### Вибіркове середнє

$ \overline{mac prices} = \frac{200+250*3+289.5+300*2}{7} = 262.7857 $

$ \overline{milk prices} = \frac{195.53+187.99+178.47+151.13+205.85+185.31+151.42}{7} = 179.3857 $

In [2]:
# calculate mean

mean(mac_prices)
mean(milk_prices)

[1] 262.7857

[1] 179.3857

#### Середнє геометричне

$ GM(macprices) = \sqrt[7]{200\cdot 250^3\cdot 289.5\cdot 300^2} = 260.5075 $

$ GM(milkprices) = \sqrt[7]{195.53\cdot 187.99\cdot 178.47\cdot 151.13\cdot 205.85\cdot 185.31\cdot 151.42} = 178.2905 $

In [3]:
# calculate GM

exp(mean(log(mac_prices)))
exp(mean(log(milk_prices)))

[1] 260.5075

[1] 178.2905

#### Середнє гармонійне

$ HM(macprices) = \frac{7}{\frac{1}{200}+\frac{3}{250}+\frac{1}{289.5}+\frac{2}{300}} = 258.1035 $

$ HM(milkprices) = \frac{7}{\frac{1}{195.53}+\frac{1}{187.99}+\frac{1}{178.47}+\frac{1}{151.13}+\frac{1}{205.85}+\frac{1}{185.31}+\frac{1}{151.42}} = 177.1607 $

In [4]:
# calculate HM

length(mac_prices)/sum(1/mac_prices)
length(milk_prices)/sum(1/milk_prices)

[1] 258.1035

[1] 177.1607

#### Ранжирований ряд:

range    |   1   |   2   |   3   |  4  |   5   |   6   |   7
---------- | ----- | ----- | ----- | --- | ----- | ----- | -----
mac_prices | 200.0 | 250.0 | 250.0 | 250 | 289.5 | 300.0 | 300.0
milk_prices| 151.13 | 151.42 | 178.47 | 185.31 | 187.99 | 195.53 | 205.85

In [5]:
# get sorted range

mac_prices_sorted  = sort(mac_prices)
milk_prices_sorted = sort(milk_prices)

#### Медіана

med(mac_prices)  = 250

med(milk_prices) = 185.31

In [6]:
# calculate median

median(mac_prices_sorted)
median(milk_prices_sorted)

[1] 250

[1] 185.31

#### Середина діапазону

Вибірка | Середина діапазону
------- | ------------------
mac_prices | 250
milk_prices | 178.49

In [7]:
# calculate midrange

(max(mac_prices)+min(mac_prices))/2
(max(milk_prices)+min(milk_prices))/2

[1] 250

[1] 178.49

#### Дисперсія

##### Вибіркова дисперсія:

$ S^2(mac prices) = \frac{(200-262.7857)^2+3*(250-262.7857)^2+(289.5-262.7857)^2+2*(300-262.7857)^2}{7} = 1130.847 $

$ S^2(milk prices) = \frac{(151.13-179.3857)^2+(151.42-179.3857)^2+(178.47-179.3857)^2+(185.31-179.3857)^2+(187.99-179.3857)^2+(195.53-179.3857)^2+(205.85-179.3857)^2}{7} = 378.7761 $

##### Виправлена дисперсія:

$ S_0^2(mac prices) = \frac{(200-262.7857)^2+3*(250-262.7857)^2+(289.5-262.7857)^2+2*(300-262.7857)^2}{6} = 1319.321 $

$ S^2(milk prices) = \frac{(151.13-179.3857)^2+(151.42-179.3857)^2+(178.47-179.3857)^2+(185.31-179.3857)^2+(187.99-179.3857)^2+(195.53-179.3857)^2+(205.85-179.3857)^2}{6} = 441.9054 $

In [8]:
# calculate variance

var(mac_prices)
var(milk_prices)

[1] 1319.321

[1] 441.9054

#### Середньоквадратичне відхилення

##### Відхилення:

$ S(macprices) = \sqrt{1130.847} = 33.62807 $

$ S(milkprices) = \sqrt{378.7761} = 19.46217 $

##### Виправлене відхилення:

$ S_0(macprices) = \sqrt{1319.321} = 36.32246 $

$ S_0(milkprices) = \sqrt{378.7761} = 21.02155 $

In [9]:
# calculate standard deviation

sd_mac  = var(mac_prices) ^0.5
sd_milk = var(milk_prices)^0.5

sd_mac
sd_milk

[1] 36.32246

[1] 21.02155

### IQR


range    |   1   |   2   |   3   |  4  |   5   |   6   |   7
---------- | ----- | ----- | ----- | --- | ----- | ----- | -----
mac_prices | 200.0 | __250.0__ | 250.0 | __250__ | 289.5 | __300.0__ | 300.0
milk_prices| 151.13 | __151.42__ | 178.47 | __185.31__ | 187.99 | __195.53__ | 205.85

IQR(mac_prices) = 300 - 250 = 50

IQR(milk_prices) = 195.53 - 151.42 = 44.11

##### З урахуванням медіани:

IQR(mac_prices) = $ \frac{300+289.5}{2} - 250  = 44.75 $

IQR(milk_prices) = $ \frac{195.53 + 187.99}{2} - \frac{151.42 + 178.47}{2} = 26.815 $

In [10]:
# calculate IQR

IQR(mac_prices_sorted)
IQR(milk_prices_sorted)

[1] 44.75

[1] 26.815

#### Ширина діапазону

Вибірка | Ширина діапазону
------- | ------------------
mac_prices | 100
milk_prices | 54.72

In [11]:
# calculate range width

(max(mac_prices)-min(mac_prices))
(max(milk_prices)-min(milk_prices))

[1] 100

[1] 54.72

#### Variation coefficient

$ CV(mac prices) = \frac{S(mac prices)}{\overline{mac prices}} = \frac{33.62807}{262.7857} = 0.1279677 $

$ CV(milk prices) = \frac{S(milk prices)}{\overline{mac prices}} = \frac{19.46217}{179.3857} = 0.1084934 $

##### З виправленим відхиленням:

$ CV_0(mac prices) = \frac{S_0(mac_prices)}{\overline{mac prices}} = \frac{36.32246}{262.7857} = 0.1382208 $

$ CV_0(milk prices) = \frac{S_0(milk_prices)}{\overline{mac prices}} = \frac{21.02155}{179.3857} = 0.1171863 $

In [12]:
# calculate relative standard deviation (RSD) (CV)

sd_mac/mean(mac_prices)
sd_milk/mean(milk_prices)

[1] 0.1382208

[1] 0.1171863

### Висновки

* R рахує виправлені характеристики
* Вручну рахувати довго і неприємно
* Дуже хочеться попрацювати з датасетами в форматі .csv, а не власноруч копіпащеними, готова парсери писати :)
* Чекаю на інструменти візуалізації, без них нині важко

* Загалом R на мій перший погляд не сильно відрізняється від наукових пакетів Python 3